discord:
    modules:
    - base.userfacing
    - test
    - admin
    - karma
    - managed_cat
    - pin
    - linker

sql:
    path: srv.0.db

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        standard:
            format: "%(levelname)-8s %(name)-15s: %(message)s"
            datefmt: "%d/%m %H:%M:%S"
    handlers:
        default:
            level: DEBUG
            formatter: standard
            class: logging.StreamHandler
    loggers:
        discord:
            handlers: [default]
            level: INFO
            propagate: false
        websockets:
            handlers: [default]
            level: INFO
            propagate: false
        '':
            handlers: [default]
            level: INFO
            propagate: false
